### ISSUE TITLE
Null Pointer Exception at first test run

### ISSUE THREAD

**Issue by jayakumarss** [eugenepolschikov/testng-demo#1]
Downloaded the application, configured the hub and both nodes as per the instructions provided in the blog: https://experitest.com/blogs/testng_framework_maven/

I am getting the following exception when I am running: mvn clean test -DTestNG.suite.name=ParallelTestsSuiteWithListeners

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
...
... TestNG 6.14.3 by Cédric Beust (cedric@beust.com)
...

Test Method BeforeInvocation is started. Current ThreadId:14
Test Method BeforeInvocation is started. Current ThreadId:15
2019-11-10 00:01:38,051 |INFO  [TestNG-test=second thread in parallel execution -1] com.testngdemo.automation.parallelexecution.TLDriverFactory:27 - creating driver instance on the runnning GRID INFRA: http://localhost:4444/wd/hub#### 
2019-11-10 00:01:38,063 |INFO  [TestNG-test=second thread in parallel execution -1] com.testngdemo.automation.parallelexecution.TLDriverFactory:29 - setting driver instance specifically for firefox
Nov 10, 2019 12:01:38 AM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Test Method AfterInvocation is started. Current ThreadId:14
2019-11-10 00:01:41,271 |INFO  [TestNG-test=first thread in parallel execution-1] com.testngdemo.automation.parallelexecution.TLDriverFactory:27 - creating driver instance on the runnning GRID INFRA: http://localhost:4444/wd/hub#### 
2019-11-10 00:01:41,273 |INFO  [TestNG-test=first thread in parallel execution-1] com.testngdemo.automation.parallelexecution.TLDriverFactory:36 - setting driver instance specifically for chrome
Nov 10, 2019 12:01:41 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Test Method AfterInvocation is started. Current ThreadId:15
Test Method BeforeInvocation is started. Current ThreadId:15
2019-11-10 00:01:41,464 |INFO  [TestNG-test=first thread in parallel execution-1] com.testngdemo.automation.parallelexecution.TLDriverFactory:27 - creating driver instance on the runnning GRID INFRA: http://localhost:4444/wd/hub#### 
2019-11-10 00:01:41,464 |INFO  [TestNG-test=first thread in parallel execution-1] com.testngdemo.automation.parallelexecution.TLDriverFactory:36 - setting driver instance specifically for chrome
Nov 10, 2019 12:01:41 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Test Method AfterInvocation is started. Current ThreadId:15
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 7.203 sec <<< FAILURE! - in TestSuite
googleDoAnotherSimpleSearchByQuery(com.testngdemo.automation.functional.GoogleLandingPageFirstTest)  Time elapsed: 3.275 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.testngdemo.automation.listeners.paralleltests.InvokedMethodListenerWithScreenshots.afterInvocation(InvokedMethodListenerWithScreenshots.java:41)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:493)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jayakumarss** [comment]
Resolved the issue by moving the .exe files for each driver (chrome and firefox) into the same directory where the selenium-server-standalone and the other 2 commands for running each node are being executed.
